name: 03-workflow-runners
on:
    push:
    workflow_dispatch:

jobs:
    ubuntu-echo:
        runs-on: ubuntu-latest
        steps:
            - name: Show OS
              run: |
                "This jon is running on an Ubuntu runner"
                 echo "The runner is $RUNNER_OS" 
    windows-echo:
        runs-on: windows-lates
        steps:
            - name: Show OS
              run: |
                "This job is running on a Windows runner"
                echo "The runner is $RUNNER_OS"